cdc_raw:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: cdc_raw.duckdb
      schema: main
      threads: 1
      extensions:
        - httpfs
      settings:
        s3_endpoint: "localhost:9000"
        s3_access_key_id: "minioadmin"
        s3_secret_access_key: "minioadmin"
        s3_url_style: "path"
        s3_use_ssl: false
